// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwVONDk3MiYmWSudcXCpBpEN8nqVYH0sM',
    appId: '1:1054362437016:web:dd06f619991b3486ac17ed',
    messagingSenderId: '1054362437016',
    projectId: 'snkr-2dd17',
    authDomain: 'snkr-2dd17.firebaseapp.com',
    storageBucket: 'snkr-2dd17.appspot.com',
    measurementId: 'G-XZSF4XRGX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgMRaB52fY9qYtTUo3-SpA44LO-z0dBEw',
    appId: '1:1054362437016:android:e59f02150e794f45ac17ed',
    messagingSenderId: '1054362437016',
    projectId: 'snkr-2dd17',
    storageBucket: 'snkr-2dd17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAbDSfUC3L9UNzQesPKKARDXx2SVOuNUQ',
    appId: '1:1054362437016:ios:bf314483160db7e0ac17ed',
    messagingSenderId: '1054362437016',
    projectId: 'snkr-2dd17',
    storageBucket: 'snkr-2dd17.appspot.com',
    iosBundleId: 'com.example.snkrFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAbDSfUC3L9UNzQesPKKARDXx2SVOuNUQ',
    appId: '1:1054362437016:ios:bf314483160db7e0ac17ed',
    messagingSenderId: '1054362437016',
    projectId: 'snkr-2dd17',
    storageBucket: 'snkr-2dd17.appspot.com',
    iosBundleId: 'com.example.snkrFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwVONDk3MiYmWSudcXCpBpEN8nqVYH0sM',
    appId: '1:1054362437016:web:82cda11831399beaac17ed',
    messagingSenderId: '1054362437016',
    projectId: 'snkr-2dd17',
    authDomain: 'snkr-2dd17.firebaseapp.com',
    storageBucket: 'snkr-2dd17.appspot.com',
    measurementId: 'G-X2PQMCVHYG',
  );
}
